# ~/.config/starship.toml

# GENERAL SETTINGS
add_newline = true
format = "\n$directory$git_branch$git_status$package$nodejs$python$golang$custom_info$cmd_duration$line_break$jobs$character "

# DIRECTORY MODULE
[directory]
truncation_length = 3
truncation_symbol = "…"
format = "[$path]($style) "
style = "bold cyan"

# GIT BRANCH MODULE
[git_branch]
symbol = " "  # Nerd Font's branch icon
style = "bold yellow"
format = "[$symbol$branch]($style) "

# GIT STATUS MODULE
[git_status]
conflicted = " "
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕ ${count}"
untracked = "★"
stashed = " "
modified = "✏️ "
format = "[$all_status]($style) "
style = "bold red"

# PACKAGE MODULE
[package]
symbol = "📦 "
format = "[$symbol$version]($style) "
style = "bold blue"

# NODE.JS MODULE
[nodejs]
symbol = " "  # Node icon
style = "bold green"
format = "[$symbol$version]($style) "

# PYTHON MODULE
[python]
symbol = "🐍 "
style = "bold green"
format = "[<${virtualenv}> $symbol$version ]($style) "  # Display virtualenv name
disabled = false
detect_extensions = ["py"]
detect_files = ["Pipfile", "pyproject.toml", "requirements.txt", ".python-version"]
# detect_virtualenv = true  # Show only when a virtual environment is active

# GO MODULE
[golang]
symbol = " "
style = "bold cyan"
format = "[$symbol$version]($style) "

# CUSTOM MODULE for displaying project-specific files
[custom.project_files]
command = 'ls | grep -E "Dockerfile|\\.env|README\\.md"'
symbol = "🔍 "
style = "bold yellow"
format = "[$symbol $output]($style) "
disabled = false

# CMD DURATION MODULE
[cmd_duration]
min_time = 2000  # Show only if command took > 2 seconds
format = "⏱️ [$duration]($style) "
style = "bold yellow"

# JOBS MODULE
[jobs]
symbol = "🧵 "
threshold = 2
style = "bold purple"
format = "[$symbol$number]($style) "

# CHARACTER MODULE
[character]
success_symbol = "[➤](bold #c5ff05) "
error_symbol = "[✗](bold red) "
